### ISSUE TITLE
[feature request] Multiple meanings like in deepL app.

### ISSUE THREAD

**Issue by maosin77** [DeepLcom/deepl-api-issues#13]
Hello, 

First of all, thank you for all great job! DeepL is such a great tool!

I am using your app on daily basis and API in my side project. I am wondering is there a chance to get multple meanings for single translation as we can get in app?

I see that I can use 'context' prop which is great, but still having various meaning of single word would be something great. 

![image](https://github.com/DeepLcom/deepl-node/assets/73907125/4a4301ff-9d2d-467d-a412-2d309253a03a)

**Comment by JanEbbing** [comment]
Hi @maosin77 , unfortunately we don't offer alternatives in the API currently, the feature is only available in our apps.
