### ISSUE TITLE
Glossary not working properly

### ISSUE THREAD

**Issue by Nephel1a** [DeepLcom/deepl-api-issues#19]
Yesterday such an error appeared that there is no translation from English to Russian in the glossary. Even the existing glossary is not applied, although the usual translation from English to Russian is available. I would like to know how soon this problem will be solved, because I can not work normally.

**Comment by JanEbbing** [comment]
Hi, sorry but your problem description is too vague for me to help. Could you please share at least the glossary you're using and how you're calling the API (code or cURL command, make sure to cut out your API key). Ideally as a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by Nephel1a** [comment]
Oh, sorry. Surprisingly, the problem is already solved and the glossaries are working correctly. I couldn't find where to get the API key, but from what I've read, I need to have the DeppL API, and I only use DeepL Pro. But the important thing is that the problem is solved and I hope it doesn't happen again. I apologize for bothering you guys.
