### ISSUE TITLE
US and GB english translation behavior

### ISSUE THREAD

**Issue by dombajova** [DeepLcom/deepl-api-issues#21]
Hi, I have used translation from English to US english with the following results:

English
Target text: `Our neighbours are our best friends and we work in the same organisation.`

EN-US 
Translated text:  `Our neighbours are our best friends and we work in the same organisation.`

I would, however, expect the result to reflect the particularities of American English so `Our neighbors are our best friends and we work in the same organization.`
Is this not supported scenario at the moment? Thank you for your answer

**Comment by JanEbbing** [comment]
Hi, thanks for your report! Please note that translation from british to american english (and vice versa) is currently not supported, the API will just return your input text. If you start in a language other than english, it will correctly spell `neighbor/neighbour` according to the variant.

For example German to BE:

`Unsere Nachbarn sind unsere besten Freunde und wir arbeiten in der gleichen Organisation.` => `Our neighbours are our best friends and we work in the same organisation.`

German to AE:

`Unsere Nachbarn sind unsere besten Freunde und wir arbeiten in der gleichen Organisation.` => `Our neighbors are our best friends and we work in the same organization.`

For Spanish to BE:

`Nuestros vecinos son nuestros mejores amigos y trabajamos en la misma organización.` => `Our neighbours are our best friends and we work in the same organisation.`

Spanish to AE:

`Nuestros vecinos son nuestros mejores amigos y trabajamos en la misma organización.` => `Our neighbors are our best friends and we work in the same organization.`

If you only have the source text available in English, a workaround would be to use a pivot language (ideally a high-resource one, for example German or Spanish), translate into that one first, and then back into the english variant of your choosing. This sometimes leads to suboptimal translations unfortunately, but works pretty well.

**Comment by JanEbbing** [comment]
Sorry just to clarify, this not only applies to english but to all languages with variant (currently English and Portuguese). You cannot translate from English/Portuguese to one of the variants of the same language (English to PT-PT/PT-BR or PT to EN-US/EN-GB would work obviously).
